version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=registration_db
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=registration_db
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - db
    restart: always
    networks:
      - app-network
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTPサーバーポート
      - "8025:8025" # Web UIポート
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
